### ISSUE TITLE
生成される問題フォルダを `src` 以下にするか検討

### ISSUE THREAD

**Issue by seijinrosen** [seijinrosen/acac#27]
- src/algo-method.com/...
- src/atcoder.jp/...

のような感じ。増えてきたら汚くなるから。

**Comment by seijinrosen** [comment]
`src` だと都合が悪い場合がありそうなので、別の名前を検討する。
rust への対応とか。

**Comment by seijinrosen** [comment]
`acac.toml` で

```toml
workspace_dir = "."
workspace_dir = "sites"
```

のように指定できるようにする？
